version: '3.4'


services:
  emulate:
    image: lukechilds/dockerpi
    ports:
      - "5022:5022"
    volumes:
      - ./images:/images
      - ./images/yourZippedImage:/filesystem.zip
      - ./entrypoint.sh:/entrypoint.sh
    command: pi2